version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080